//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consumo.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Equipos", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Equipos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        private double PrecioField;
        
        private int StockField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdProducto {
            get {
                return this.IdProductoField;
            }
            set {
                if ((this.IdProductoField.Equals(value) != true)) {
                    this.IdProductoField = value;
                    this.RaisePropertyChanged("IdProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServiciosSoap")]
    public interface ServiciosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Consumo.ServiceReference1.HelloWorldResponse HelloWorld(Consumo.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.HelloWorldResponse> HelloWorldAsync(Consumo.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Saludar", ReplyAction="*")]
        Consumo.ServiceReference1.SaludarResponse Saludar(Consumo.ServiceReference1.SaludarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Saludar", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.SaludarResponse> SaludarAsync(Consumo.ServiceReference1.SaludarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento mensaje del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarLog", ReplyAction="*")]
        Consumo.ServiceReference1.GuardarLogResponse GuardarLog(Consumo.ServiceReference1.GuardarLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarLog", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.GuardarLogResponse> GuardarLogAsync(Consumo.ServiceReference1.GuardarLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sumar", ReplyAction="*")]
        int Sumar(int numero1, int numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sumar", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SumarAsync(int numero1, int numero2);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerfrutasResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Obtenerfrutas", ReplyAction="*")]
        Consumo.ServiceReference1.ObtenerfrutasResponse Obtenerfrutas(Consumo.ServiceReference1.ObtenerfrutasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Obtenerfrutas", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.ObtenerfrutasResponse> ObtenerfrutasAsync(Consumo.ServiceReference1.ObtenerfrutasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento frutas del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarFrutas", ReplyAction="*")]
        Consumo.ServiceReference1.GuardarFrutasResponse GuardarFrutas(Consumo.ServiceReference1.GuardarFrutasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarFrutas", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.GuardarFrutasResponse> GuardarFrutasAsync(Consumo.ServiceReference1.GuardarFrutasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerEquiposResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerEquipos", ReplyAction="*")]
        Consumo.ServiceReference1.ObtenerEquiposResponse ObtenerEquipos(Consumo.ServiceReference1.ObtenerEquiposRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerEquipos", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.ObtenerEquiposResponse> ObtenerEquiposAsync(Consumo.ServiceReference1.ObtenerEquiposRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento equipos del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarEquipos", ReplyAction="*")]
        Consumo.ServiceReference1.GuardarEquiposResponse GuardarEquipos(Consumo.ServiceReference1.GuardarEquiposRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarEquipos", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.GuardarEquiposResponse> GuardarEquiposAsync(Consumo.ServiceReference1.GuardarEquiposRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento xml del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarXML", ReplyAction="*")]
        Consumo.ServiceReference1.GuardarXMLResponse GuardarXML(Consumo.ServiceReference1.GuardarXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarXML", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.GuardarXMLResponse> GuardarXMLAsync(Consumo.ServiceReference1.GuardarXMLRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento RetornarJsonResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetornarJson", ReplyAction="*")]
        Consumo.ServiceReference1.RetornarJsonResponse RetornarJson(Consumo.ServiceReference1.RetornarJsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetornarJson", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.RetornarJsonResponse> RetornarJsonAsync(Consumo.ServiceReference1.RetornarJsonRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento json del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarJson", ReplyAction="*")]
        Consumo.ServiceReference1.GuardarJsonResponse GuardarJson(Consumo.ServiceReference1.GuardarJsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarJson", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.GuardarJsonResponse> GuardarJsonAsync(Consumo.ServiceReference1.GuardarJsonRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerProductosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerProductos", ReplyAction="*")]
        Consumo.ServiceReference1.ObtenerProductosResponse ObtenerProductos(Consumo.ServiceReference1.ObtenerProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerProductos", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.ObtenerProductosResponse> ObtenerProductosAsync(Consumo.ServiceReference1.ObtenerProductosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerProductoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerProducto", ReplyAction="*")]
        Consumo.ServiceReference1.ObtenerProductoResponse ObtenerProducto(Consumo.ServiceReference1.ObtenerProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.ObtenerProductoResponse> ObtenerProductoAsync(Consumo.ServiceReference1.ObtenerProductoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento producto del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AcualizarProducto", ReplyAction="*")]
        Consumo.ServiceReference1.AcualizarProductoResponse AcualizarProducto(Consumo.ServiceReference1.AcualizarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AcualizarProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.AcualizarProductoResponse> AcualizarProductoAsync(Consumo.ServiceReference1.AcualizarProductoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento producto del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarProducto", ReplyAction="*")]
        Consumo.ServiceReference1.GuardarProductoResponse GuardarProducto(Consumo.ServiceReference1.GuardarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.GuardarProductoResponse> GuardarProductoAsync(Consumo.ServiceReference1.GuardarProductoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Consumo.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Consumo.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaludarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Saludar", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.SaludarRequestBody Body;
        
        public SaludarRequest() {
        }
        
        public SaludarRequest(Consumo.ServiceReference1.SaludarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaludarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        public SaludarRequestBody() {
        }
        
        public SaludarRequestBody(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaludarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaludarResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.SaludarResponseBody Body;
        
        public SaludarResponse() {
        }
        
        public SaludarResponse(Consumo.ServiceReference1.SaludarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaludarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SaludarResult;
        
        public SaludarResponseBody() {
        }
        
        public SaludarResponseBody(string SaludarResult) {
            this.SaludarResult = SaludarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarLog", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.GuardarLogRequestBody Body;
        
        public GuardarLogRequest() {
        }
        
        public GuardarLogRequest(Consumo.ServiceReference1.GuardarLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mensaje;
        
        public GuardarLogRequestBody() {
        }
        
        public GuardarLogRequestBody(string mensaje) {
            this.mensaje = mensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarLogResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.GuardarLogResponseBody Body;
        
        public GuardarLogResponse() {
        }
        
        public GuardarLogResponse(Consumo.ServiceReference1.GuardarLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarLogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GuardarLogResult;
        
        public GuardarLogResponseBody() {
        }
        
        public GuardarLogResponseBody(string GuardarLogResult) {
            this.GuardarLogResult = GuardarLogResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerfrutasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Obtenerfrutas", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.ObtenerfrutasRequestBody Body;
        
        public ObtenerfrutasRequest() {
        }
        
        public ObtenerfrutasRequest(Consumo.ServiceReference1.ObtenerfrutasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerfrutasRequestBody {
        
        public ObtenerfrutasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerfrutasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerfrutasResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.ObtenerfrutasResponseBody Body;
        
        public ObtenerfrutasResponse() {
        }
        
        public ObtenerfrutasResponse(Consumo.ServiceReference1.ObtenerfrutasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerfrutasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Consumo.ServiceReference1.ArrayOfString ObtenerfrutasResult;
        
        public ObtenerfrutasResponseBody() {
        }
        
        public ObtenerfrutasResponseBody(Consumo.ServiceReference1.ArrayOfString ObtenerfrutasResult) {
            this.ObtenerfrutasResult = ObtenerfrutasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarFrutasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarFrutas", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.GuardarFrutasRequestBody Body;
        
        public GuardarFrutasRequest() {
        }
        
        public GuardarFrutasRequest(Consumo.ServiceReference1.GuardarFrutasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarFrutasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Consumo.ServiceReference1.ArrayOfString frutas;
        
        public GuardarFrutasRequestBody() {
        }
        
        public GuardarFrutasRequestBody(Consumo.ServiceReference1.ArrayOfString frutas) {
            this.frutas = frutas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarFrutasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarFrutasResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.GuardarFrutasResponseBody Body;
        
        public GuardarFrutasResponse() {
        }
        
        public GuardarFrutasResponse(Consumo.ServiceReference1.GuardarFrutasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarFrutasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GuardarFrutasResult;
        
        public GuardarFrutasResponseBody() {
        }
        
        public GuardarFrutasResponseBody(string GuardarFrutasResult) {
            this.GuardarFrutasResult = GuardarFrutasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerEquiposRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerEquipos", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.ObtenerEquiposRequestBody Body;
        
        public ObtenerEquiposRequest() {
        }
        
        public ObtenerEquiposRequest(Consumo.ServiceReference1.ObtenerEquiposRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerEquiposRequestBody {
        
        public ObtenerEquiposRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerEquiposResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerEquiposResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.ObtenerEquiposResponseBody Body;
        
        public ObtenerEquiposResponse() {
        }
        
        public ObtenerEquiposResponse(Consumo.ServiceReference1.ObtenerEquiposResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerEquiposResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Consumo.ServiceReference1.Equipos[] ObtenerEquiposResult;
        
        public ObtenerEquiposResponseBody() {
        }
        
        public ObtenerEquiposResponseBody(Consumo.ServiceReference1.Equipos[] ObtenerEquiposResult) {
            this.ObtenerEquiposResult = ObtenerEquiposResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarEquiposRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarEquipos", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.GuardarEquiposRequestBody Body;
        
        public GuardarEquiposRequest() {
        }
        
        public GuardarEquiposRequest(Consumo.ServiceReference1.GuardarEquiposRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarEquiposRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Consumo.ServiceReference1.Equipos[] equipos;
        
        public GuardarEquiposRequestBody() {
        }
        
        public GuardarEquiposRequestBody(Consumo.ServiceReference1.Equipos[] equipos) {
            this.equipos = equipos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarEquiposResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarEquiposResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.GuardarEquiposResponseBody Body;
        
        public GuardarEquiposResponse() {
        }
        
        public GuardarEquiposResponse(Consumo.ServiceReference1.GuardarEquiposResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarEquiposResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GuardarEquiposResult;
        
        public GuardarEquiposResponseBody() {
        }
        
        public GuardarEquiposResponseBody(string GuardarEquiposResult) {
            this.GuardarEquiposResult = GuardarEquiposResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarXML", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.GuardarXMLRequestBody Body;
        
        public GuardarXMLRequest() {
        }
        
        public GuardarXMLRequest(Consumo.ServiceReference1.GuardarXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public GuardarXMLRequestBody() {
        }
        
        public GuardarXMLRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarXMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.GuardarXMLResponseBody Body;
        
        public GuardarXMLResponse() {
        }
        
        public GuardarXMLResponse(Consumo.ServiceReference1.GuardarXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GuardarXMLResult;
        
        public GuardarXMLResponseBody() {
        }
        
        public GuardarXMLResponseBody(string GuardarXMLResult) {
            this.GuardarXMLResult = GuardarXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetornarJsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetornarJson", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.RetornarJsonRequestBody Body;
        
        public RetornarJsonRequest() {
        }
        
        public RetornarJsonRequest(Consumo.ServiceReference1.RetornarJsonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RetornarJsonRequestBody {
        
        public RetornarJsonRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetornarJsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetornarJsonResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.RetornarJsonResponseBody Body;
        
        public RetornarJsonResponse() {
        }
        
        public RetornarJsonResponse(Consumo.ServiceReference1.RetornarJsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetornarJsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RetornarJsonResult;
        
        public RetornarJsonResponseBody() {
        }
        
        public RetornarJsonResponseBody(string RetornarJsonResult) {
            this.RetornarJsonResult = RetornarJsonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarJsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarJson", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.GuardarJsonRequestBody Body;
        
        public GuardarJsonRequest() {
        }
        
        public GuardarJsonRequest(Consumo.ServiceReference1.GuardarJsonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarJsonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string json;
        
        public GuardarJsonRequestBody() {
        }
        
        public GuardarJsonRequestBody(string json) {
            this.json = json;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarJsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarJsonResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.GuardarJsonResponseBody Body;
        
        public GuardarJsonResponse() {
        }
        
        public GuardarJsonResponse(Consumo.ServiceReference1.GuardarJsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarJsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GuardarJsonResult;
        
        public GuardarJsonResponseBody() {
        }
        
        public GuardarJsonResponseBody(string GuardarJsonResult) {
            this.GuardarJsonResult = GuardarJsonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerProductosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerProductos", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.ObtenerProductosRequestBody Body;
        
        public ObtenerProductosRequest() {
        }
        
        public ObtenerProductosRequest(Consumo.ServiceReference1.ObtenerProductosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerProductosRequestBody {
        
        public ObtenerProductosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerProductosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.ObtenerProductosResponseBody Body;
        
        public ObtenerProductosResponse() {
        }
        
        public ObtenerProductosResponse(Consumo.ServiceReference1.ObtenerProductosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerProductosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerProductosResult;
        
        public ObtenerProductosResponseBody() {
        }
        
        public ObtenerProductosResponseBody(string ObtenerProductosResult) {
            this.ObtenerProductosResult = ObtenerProductosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerProducto", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.ObtenerProductoRequestBody Body;
        
        public ObtenerProductoRequest() {
        }
        
        public ObtenerProductoRequest(Consumo.ServiceReference1.ObtenerProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public ObtenerProductoRequestBody() {
        }
        
        public ObtenerProductoRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerProductoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.ObtenerProductoResponseBody Body;
        
        public ObtenerProductoResponse() {
        }
        
        public ObtenerProductoResponse(Consumo.ServiceReference1.ObtenerProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Consumo.ServiceReference1.Producto ObtenerProductoResult;
        
        public ObtenerProductoResponseBody() {
        }
        
        public ObtenerProductoResponseBody(Consumo.ServiceReference1.Producto ObtenerProductoResult) {
            this.ObtenerProductoResult = ObtenerProductoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AcualizarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AcualizarProducto", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.AcualizarProductoRequestBody Body;
        
        public AcualizarProductoRequest() {
        }
        
        public AcualizarProductoRequest(Consumo.ServiceReference1.AcualizarProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AcualizarProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Consumo.ServiceReference1.Producto producto;
        
        public AcualizarProductoRequestBody() {
        }
        
        public AcualizarProductoRequestBody(Consumo.ServiceReference1.Producto producto) {
            this.producto = producto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AcualizarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AcualizarProductoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.AcualizarProductoResponseBody Body;
        
        public AcualizarProductoResponse() {
        }
        
        public AcualizarProductoResponse(Consumo.ServiceReference1.AcualizarProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AcualizarProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AcualizarProductoResult;
        
        public AcualizarProductoResponseBody() {
        }
        
        public AcualizarProductoResponseBody(string AcualizarProductoResult) {
            this.AcualizarProductoResult = AcualizarProductoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarProducto", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.GuardarProductoRequestBody Body;
        
        public GuardarProductoRequest() {
        }
        
        public GuardarProductoRequest(Consumo.ServiceReference1.GuardarProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Consumo.ServiceReference1.Producto producto;
        
        public GuardarProductoRequestBody() {
        }
        
        public GuardarProductoRequestBody(Consumo.ServiceReference1.Producto producto) {
            this.producto = producto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarProductoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.GuardarProductoResponseBody Body;
        
        public GuardarProductoResponse() {
        }
        
        public GuardarProductoResponse(Consumo.ServiceReference1.GuardarProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GuardarProductoResult;
        
        public GuardarProductoResponseBody() {
        }
        
        public GuardarProductoResponseBody(int GuardarProductoResult) {
            this.GuardarProductoResult = GuardarProductoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiciosSoapChannel : Consumo.ServiceReference1.ServiciosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosSoapClient : System.ServiceModel.ClientBase<Consumo.ServiceReference1.ServiciosSoap>, Consumo.ServiceReference1.ServiciosSoap {
        
        public ServiciosSoapClient() {
        }
        
        public ServiciosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiciosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumo.ServiceReference1.HelloWorldResponse Consumo.ServiceReference1.ServiciosSoap.HelloWorld(Consumo.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Consumo.ServiceReference1.HelloWorldRequest inValue = new Consumo.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Consumo.ServiceReference1.HelloWorldRequestBody();
            Consumo.ServiceReference1.HelloWorldResponse retVal = ((Consumo.ServiceReference1.ServiciosSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.HelloWorldResponse> Consumo.ServiceReference1.ServiciosSoap.HelloWorldAsync(Consumo.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumo.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            Consumo.ServiceReference1.HelloWorldRequest inValue = new Consumo.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Consumo.ServiceReference1.HelloWorldRequestBody();
            return ((Consumo.ServiceReference1.ServiciosSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumo.ServiceReference1.SaludarResponse Consumo.ServiceReference1.ServiciosSoap.Saludar(Consumo.ServiceReference1.SaludarRequest request) {
            return base.Channel.Saludar(request);
        }
        
        public string Saludar(string nombre) {
            Consumo.ServiceReference1.SaludarRequest inValue = new Consumo.ServiceReference1.SaludarRequest();
            inValue.Body = new Consumo.ServiceReference1.SaludarRequestBody();
            inValue.Body.nombre = nombre;
            Consumo.ServiceReference1.SaludarResponse retVal = ((Consumo.ServiceReference1.ServiciosSoap)(this)).Saludar(inValue);
            return retVal.Body.SaludarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.SaludarResponse> Consumo.ServiceReference1.ServiciosSoap.SaludarAsync(Consumo.ServiceReference1.SaludarRequest request) {
            return base.Channel.SaludarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumo.ServiceReference1.SaludarResponse> SaludarAsync(string nombre) {
            Consumo.ServiceReference1.SaludarRequest inValue = new Consumo.ServiceReference1.SaludarRequest();
            inValue.Body = new Consumo.ServiceReference1.SaludarRequestBody();
            inValue.Body.nombre = nombre;
            return ((Consumo.ServiceReference1.ServiciosSoap)(this)).SaludarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumo.ServiceReference1.GuardarLogResponse Consumo.ServiceReference1.ServiciosSoap.GuardarLog(Consumo.ServiceReference1.GuardarLogRequest request) {
            return base.Channel.GuardarLog(request);
        }
        
        public string GuardarLog(string mensaje) {
            Consumo.ServiceReference1.GuardarLogRequest inValue = new Consumo.ServiceReference1.GuardarLogRequest();
            inValue.Body = new Consumo.ServiceReference1.GuardarLogRequestBody();
            inValue.Body.mensaje = mensaje;
            Consumo.ServiceReference1.GuardarLogResponse retVal = ((Consumo.ServiceReference1.ServiciosSoap)(this)).GuardarLog(inValue);
            return retVal.Body.GuardarLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.GuardarLogResponse> Consumo.ServiceReference1.ServiciosSoap.GuardarLogAsync(Consumo.ServiceReference1.GuardarLogRequest request) {
            return base.Channel.GuardarLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumo.ServiceReference1.GuardarLogResponse> GuardarLogAsync(string mensaje) {
            Consumo.ServiceReference1.GuardarLogRequest inValue = new Consumo.ServiceReference1.GuardarLogRequest();
            inValue.Body = new Consumo.ServiceReference1.GuardarLogRequestBody();
            inValue.Body.mensaje = mensaje;
            return ((Consumo.ServiceReference1.ServiciosSoap)(this)).GuardarLogAsync(inValue);
        }
        
        public int Sumar(int numero1, int numero2) {
            return base.Channel.Sumar(numero1, numero2);
        }
        
        public System.Threading.Tasks.Task<int> SumarAsync(int numero1, int numero2) {
            return base.Channel.SumarAsync(numero1, numero2);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumo.ServiceReference1.ObtenerfrutasResponse Consumo.ServiceReference1.ServiciosSoap.Obtenerfrutas(Consumo.ServiceReference1.ObtenerfrutasRequest request) {
            return base.Channel.Obtenerfrutas(request);
        }
        
        public Consumo.ServiceReference1.ArrayOfString Obtenerfrutas() {
            Consumo.ServiceReference1.ObtenerfrutasRequest inValue = new Consumo.ServiceReference1.ObtenerfrutasRequest();
            inValue.Body = new Consumo.ServiceReference1.ObtenerfrutasRequestBody();
            Consumo.ServiceReference1.ObtenerfrutasResponse retVal = ((Consumo.ServiceReference1.ServiciosSoap)(this)).Obtenerfrutas(inValue);
            return retVal.Body.ObtenerfrutasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.ObtenerfrutasResponse> Consumo.ServiceReference1.ServiciosSoap.ObtenerfrutasAsync(Consumo.ServiceReference1.ObtenerfrutasRequest request) {
            return base.Channel.ObtenerfrutasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumo.ServiceReference1.ObtenerfrutasResponse> ObtenerfrutasAsync() {
            Consumo.ServiceReference1.ObtenerfrutasRequest inValue = new Consumo.ServiceReference1.ObtenerfrutasRequest();
            inValue.Body = new Consumo.ServiceReference1.ObtenerfrutasRequestBody();
            return ((Consumo.ServiceReference1.ServiciosSoap)(this)).ObtenerfrutasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumo.ServiceReference1.GuardarFrutasResponse Consumo.ServiceReference1.ServiciosSoap.GuardarFrutas(Consumo.ServiceReference1.GuardarFrutasRequest request) {
            return base.Channel.GuardarFrutas(request);
        }
        
        public string GuardarFrutas(Consumo.ServiceReference1.ArrayOfString frutas) {
            Consumo.ServiceReference1.GuardarFrutasRequest inValue = new Consumo.ServiceReference1.GuardarFrutasRequest();
            inValue.Body = new Consumo.ServiceReference1.GuardarFrutasRequestBody();
            inValue.Body.frutas = frutas;
            Consumo.ServiceReference1.GuardarFrutasResponse retVal = ((Consumo.ServiceReference1.ServiciosSoap)(this)).GuardarFrutas(inValue);
            return retVal.Body.GuardarFrutasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.GuardarFrutasResponse> Consumo.ServiceReference1.ServiciosSoap.GuardarFrutasAsync(Consumo.ServiceReference1.GuardarFrutasRequest request) {
            return base.Channel.GuardarFrutasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumo.ServiceReference1.GuardarFrutasResponse> GuardarFrutasAsync(Consumo.ServiceReference1.ArrayOfString frutas) {
            Consumo.ServiceReference1.GuardarFrutasRequest inValue = new Consumo.ServiceReference1.GuardarFrutasRequest();
            inValue.Body = new Consumo.ServiceReference1.GuardarFrutasRequestBody();
            inValue.Body.frutas = frutas;
            return ((Consumo.ServiceReference1.ServiciosSoap)(this)).GuardarFrutasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumo.ServiceReference1.ObtenerEquiposResponse Consumo.ServiceReference1.ServiciosSoap.ObtenerEquipos(Consumo.ServiceReference1.ObtenerEquiposRequest request) {
            return base.Channel.ObtenerEquipos(request);
        }
        
        public Consumo.ServiceReference1.Equipos[] ObtenerEquipos() {
            Consumo.ServiceReference1.ObtenerEquiposRequest inValue = new Consumo.ServiceReference1.ObtenerEquiposRequest();
            inValue.Body = new Consumo.ServiceReference1.ObtenerEquiposRequestBody();
            Consumo.ServiceReference1.ObtenerEquiposResponse retVal = ((Consumo.ServiceReference1.ServiciosSoap)(this)).ObtenerEquipos(inValue);
            return retVal.Body.ObtenerEquiposResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.ObtenerEquiposResponse> Consumo.ServiceReference1.ServiciosSoap.ObtenerEquiposAsync(Consumo.ServiceReference1.ObtenerEquiposRequest request) {
            return base.Channel.ObtenerEquiposAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumo.ServiceReference1.ObtenerEquiposResponse> ObtenerEquiposAsync() {
            Consumo.ServiceReference1.ObtenerEquiposRequest inValue = new Consumo.ServiceReference1.ObtenerEquiposRequest();
            inValue.Body = new Consumo.ServiceReference1.ObtenerEquiposRequestBody();
            return ((Consumo.ServiceReference1.ServiciosSoap)(this)).ObtenerEquiposAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumo.ServiceReference1.GuardarEquiposResponse Consumo.ServiceReference1.ServiciosSoap.GuardarEquipos(Consumo.ServiceReference1.GuardarEquiposRequest request) {
            return base.Channel.GuardarEquipos(request);
        }
        
        public string GuardarEquipos(Consumo.ServiceReference1.Equipos[] equipos) {
            Consumo.ServiceReference1.GuardarEquiposRequest inValue = new Consumo.ServiceReference1.GuardarEquiposRequest();
            inValue.Body = new Consumo.ServiceReference1.GuardarEquiposRequestBody();
            inValue.Body.equipos = equipos;
            Consumo.ServiceReference1.GuardarEquiposResponse retVal = ((Consumo.ServiceReference1.ServiciosSoap)(this)).GuardarEquipos(inValue);
            return retVal.Body.GuardarEquiposResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.GuardarEquiposResponse> Consumo.ServiceReference1.ServiciosSoap.GuardarEquiposAsync(Consumo.ServiceReference1.GuardarEquiposRequest request) {
            return base.Channel.GuardarEquiposAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumo.ServiceReference1.GuardarEquiposResponse> GuardarEquiposAsync(Consumo.ServiceReference1.Equipos[] equipos) {
            Consumo.ServiceReference1.GuardarEquiposRequest inValue = new Consumo.ServiceReference1.GuardarEquiposRequest();
            inValue.Body = new Consumo.ServiceReference1.GuardarEquiposRequestBody();
            inValue.Body.equipos = equipos;
            return ((Consumo.ServiceReference1.ServiciosSoap)(this)).GuardarEquiposAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumo.ServiceReference1.GuardarXMLResponse Consumo.ServiceReference1.ServiciosSoap.GuardarXML(Consumo.ServiceReference1.GuardarXMLRequest request) {
            return base.Channel.GuardarXML(request);
        }
        
        public string GuardarXML(string xml) {
            Consumo.ServiceReference1.GuardarXMLRequest inValue = new Consumo.ServiceReference1.GuardarXMLRequest();
            inValue.Body = new Consumo.ServiceReference1.GuardarXMLRequestBody();
            inValue.Body.xml = xml;
            Consumo.ServiceReference1.GuardarXMLResponse retVal = ((Consumo.ServiceReference1.ServiciosSoap)(this)).GuardarXML(inValue);
            return retVal.Body.GuardarXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.GuardarXMLResponse> Consumo.ServiceReference1.ServiciosSoap.GuardarXMLAsync(Consumo.ServiceReference1.GuardarXMLRequest request) {
            return base.Channel.GuardarXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumo.ServiceReference1.GuardarXMLResponse> GuardarXMLAsync(string xml) {
            Consumo.ServiceReference1.GuardarXMLRequest inValue = new Consumo.ServiceReference1.GuardarXMLRequest();
            inValue.Body = new Consumo.ServiceReference1.GuardarXMLRequestBody();
            inValue.Body.xml = xml;
            return ((Consumo.ServiceReference1.ServiciosSoap)(this)).GuardarXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumo.ServiceReference1.RetornarJsonResponse Consumo.ServiceReference1.ServiciosSoap.RetornarJson(Consumo.ServiceReference1.RetornarJsonRequest request) {
            return base.Channel.RetornarJson(request);
        }
        
        public string RetornarJson() {
            Consumo.ServiceReference1.RetornarJsonRequest inValue = new Consumo.ServiceReference1.RetornarJsonRequest();
            inValue.Body = new Consumo.ServiceReference1.RetornarJsonRequestBody();
            Consumo.ServiceReference1.RetornarJsonResponse retVal = ((Consumo.ServiceReference1.ServiciosSoap)(this)).RetornarJson(inValue);
            return retVal.Body.RetornarJsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.RetornarJsonResponse> Consumo.ServiceReference1.ServiciosSoap.RetornarJsonAsync(Consumo.ServiceReference1.RetornarJsonRequest request) {
            return base.Channel.RetornarJsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumo.ServiceReference1.RetornarJsonResponse> RetornarJsonAsync() {
            Consumo.ServiceReference1.RetornarJsonRequest inValue = new Consumo.ServiceReference1.RetornarJsonRequest();
            inValue.Body = new Consumo.ServiceReference1.RetornarJsonRequestBody();
            return ((Consumo.ServiceReference1.ServiciosSoap)(this)).RetornarJsonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumo.ServiceReference1.GuardarJsonResponse Consumo.ServiceReference1.ServiciosSoap.GuardarJson(Consumo.ServiceReference1.GuardarJsonRequest request) {
            return base.Channel.GuardarJson(request);
        }
        
        public string GuardarJson(string json) {
            Consumo.ServiceReference1.GuardarJsonRequest inValue = new Consumo.ServiceReference1.GuardarJsonRequest();
            inValue.Body = new Consumo.ServiceReference1.GuardarJsonRequestBody();
            inValue.Body.json = json;
            Consumo.ServiceReference1.GuardarJsonResponse retVal = ((Consumo.ServiceReference1.ServiciosSoap)(this)).GuardarJson(inValue);
            return retVal.Body.GuardarJsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.GuardarJsonResponse> Consumo.ServiceReference1.ServiciosSoap.GuardarJsonAsync(Consumo.ServiceReference1.GuardarJsonRequest request) {
            return base.Channel.GuardarJsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumo.ServiceReference1.GuardarJsonResponse> GuardarJsonAsync(string json) {
            Consumo.ServiceReference1.GuardarJsonRequest inValue = new Consumo.ServiceReference1.GuardarJsonRequest();
            inValue.Body = new Consumo.ServiceReference1.GuardarJsonRequestBody();
            inValue.Body.json = json;
            return ((Consumo.ServiceReference1.ServiciosSoap)(this)).GuardarJsonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumo.ServiceReference1.ObtenerProductosResponse Consumo.ServiceReference1.ServiciosSoap.ObtenerProductos(Consumo.ServiceReference1.ObtenerProductosRequest request) {
            return base.Channel.ObtenerProductos(request);
        }
        
        public string ObtenerProductos() {
            Consumo.ServiceReference1.ObtenerProductosRequest inValue = new Consumo.ServiceReference1.ObtenerProductosRequest();
            inValue.Body = new Consumo.ServiceReference1.ObtenerProductosRequestBody();
            Consumo.ServiceReference1.ObtenerProductosResponse retVal = ((Consumo.ServiceReference1.ServiciosSoap)(this)).ObtenerProductos(inValue);
            return retVal.Body.ObtenerProductosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.ObtenerProductosResponse> Consumo.ServiceReference1.ServiciosSoap.ObtenerProductosAsync(Consumo.ServiceReference1.ObtenerProductosRequest request) {
            return base.Channel.ObtenerProductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumo.ServiceReference1.ObtenerProductosResponse> ObtenerProductosAsync() {
            Consumo.ServiceReference1.ObtenerProductosRequest inValue = new Consumo.ServiceReference1.ObtenerProductosRequest();
            inValue.Body = new Consumo.ServiceReference1.ObtenerProductosRequestBody();
            return ((Consumo.ServiceReference1.ServiciosSoap)(this)).ObtenerProductosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumo.ServiceReference1.ObtenerProductoResponse Consumo.ServiceReference1.ServiciosSoap.ObtenerProducto(Consumo.ServiceReference1.ObtenerProductoRequest request) {
            return base.Channel.ObtenerProducto(request);
        }
        
        public Consumo.ServiceReference1.Producto ObtenerProducto(int id) {
            Consumo.ServiceReference1.ObtenerProductoRequest inValue = new Consumo.ServiceReference1.ObtenerProductoRequest();
            inValue.Body = new Consumo.ServiceReference1.ObtenerProductoRequestBody();
            inValue.Body.id = id;
            Consumo.ServiceReference1.ObtenerProductoResponse retVal = ((Consumo.ServiceReference1.ServiciosSoap)(this)).ObtenerProducto(inValue);
            return retVal.Body.ObtenerProductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.ObtenerProductoResponse> Consumo.ServiceReference1.ServiciosSoap.ObtenerProductoAsync(Consumo.ServiceReference1.ObtenerProductoRequest request) {
            return base.Channel.ObtenerProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumo.ServiceReference1.ObtenerProductoResponse> ObtenerProductoAsync(int id) {
            Consumo.ServiceReference1.ObtenerProductoRequest inValue = new Consumo.ServiceReference1.ObtenerProductoRequest();
            inValue.Body = new Consumo.ServiceReference1.ObtenerProductoRequestBody();
            inValue.Body.id = id;
            return ((Consumo.ServiceReference1.ServiciosSoap)(this)).ObtenerProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumo.ServiceReference1.AcualizarProductoResponse Consumo.ServiceReference1.ServiciosSoap.AcualizarProducto(Consumo.ServiceReference1.AcualizarProductoRequest request) {
            return base.Channel.AcualizarProducto(request);
        }
        
        public string AcualizarProducto(Consumo.ServiceReference1.Producto producto) {
            Consumo.ServiceReference1.AcualizarProductoRequest inValue = new Consumo.ServiceReference1.AcualizarProductoRequest();
            inValue.Body = new Consumo.ServiceReference1.AcualizarProductoRequestBody();
            inValue.Body.producto = producto;
            Consumo.ServiceReference1.AcualizarProductoResponse retVal = ((Consumo.ServiceReference1.ServiciosSoap)(this)).AcualizarProducto(inValue);
            return retVal.Body.AcualizarProductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.AcualizarProductoResponse> Consumo.ServiceReference1.ServiciosSoap.AcualizarProductoAsync(Consumo.ServiceReference1.AcualizarProductoRequest request) {
            return base.Channel.AcualizarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumo.ServiceReference1.AcualizarProductoResponse> AcualizarProductoAsync(Consumo.ServiceReference1.Producto producto) {
            Consumo.ServiceReference1.AcualizarProductoRequest inValue = new Consumo.ServiceReference1.AcualizarProductoRequest();
            inValue.Body = new Consumo.ServiceReference1.AcualizarProductoRequestBody();
            inValue.Body.producto = producto;
            return ((Consumo.ServiceReference1.ServiciosSoap)(this)).AcualizarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumo.ServiceReference1.GuardarProductoResponse Consumo.ServiceReference1.ServiciosSoap.GuardarProducto(Consumo.ServiceReference1.GuardarProductoRequest request) {
            return base.Channel.GuardarProducto(request);
        }
        
        public int GuardarProducto(Consumo.ServiceReference1.Producto producto) {
            Consumo.ServiceReference1.GuardarProductoRequest inValue = new Consumo.ServiceReference1.GuardarProductoRequest();
            inValue.Body = new Consumo.ServiceReference1.GuardarProductoRequestBody();
            inValue.Body.producto = producto;
            Consumo.ServiceReference1.GuardarProductoResponse retVal = ((Consumo.ServiceReference1.ServiciosSoap)(this)).GuardarProducto(inValue);
            return retVal.Body.GuardarProductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.GuardarProductoResponse> Consumo.ServiceReference1.ServiciosSoap.GuardarProductoAsync(Consumo.ServiceReference1.GuardarProductoRequest request) {
            return base.Channel.GuardarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumo.ServiceReference1.GuardarProductoResponse> GuardarProductoAsync(Consumo.ServiceReference1.Producto producto) {
            Consumo.ServiceReference1.GuardarProductoRequest inValue = new Consumo.ServiceReference1.GuardarProductoRequest();
            inValue.Body = new Consumo.ServiceReference1.GuardarProductoRequestBody();
            inValue.Body.producto = producto;
            return ((Consumo.ServiceReference1.ServiciosSoap)(this)).GuardarProductoAsync(inValue);
        }
    }
}
